### ISSUE TITLE
Possible Bug in Hill EQCM Coordinates

### ISSUE THREAD

**Issue by thkruz** [david-rc-dayton/pious_squid#3]
https://github.com/david-rc-dayton/pious_squid/blob/d3579648da9be426c76c910e4c12c460171e86bd/lib/src/coordinate/hill.dart#L313C5-L315C6

result is in Km/s and this branch is converting it into m/s. The problem is that it gets converted into m/s again on the next line. Unless I am missing something you will end up with mm/s whenever the ignoreCrosstrack flag is true.

**Comment by david-rc-dayton** [comment]
Was that line a `return` statement at one point? Yes.
Did I forget to remove the m/s scaling on that line after getting rid of the return statement? Also yes.

...I will fix that.

**Comment by david-rc-dayton** [comment]
Fixed in `0.3.0` release.
